name: Descarga Masiva y Comprimir
on:
  workflow_dispatch:
    inputs:
      inicio:
        description: 'ID de inicio (ej: 1)'
        required: true
        default: '1'
      fin:
        description: 'ID de fin (ej: 1000)'
        required: true
        default: '1000'
      nombre:
        description: 'Nombre del archivo ZIP'
        required: true
        default: 'ccytem'
      subir:
        description: 'Â¿Subir a GoFile? (si/no)'
        required: true
        default: 'si'

jobs:
  descargar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Instalar dependencias
        run: pip install requests
      - name: Ejecutar script
        run: python descargador.py ${{ github.event.inputs.inicio }} ${{ github.event.inputs.fin }} ${{ github.event.inputs.nombre }} ${{ github.event.inputs.subir }}
